version: '3.4'

services:
  risk.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  risk.sampleclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


 
#  kaydonsclient:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#    ports:
#      - "80"
#      - "443"
#    volumes:
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  stuartclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

 

  emmanuel_client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  
