version: '3.4'

services:
  risk.api:
    hostname: risk.api
    image: ${DOCKER_REGISTRY-}riskapi
    build:
      context: .
      dockerfile: Risk.Api/Dockerfile
    environment:
    - height=5
    - width=5
    - startingArmies=50
    ports:
    - "5000:80"
    networks:
      risknet:

  risk.sampleclient:
    hostname: risk.sampleclient
    image: ${DOCKER_REGISTRY-}risksampleclient
    build:
      context: .
      dockerfile: Risk.SampleClient/Dockerfile
    ports:
    - "5005:80"
    environment:
    - GameServer=http://risk.api
    - ClientCallbackAddress=http://risk.sampleclient
    - PlayerName=SampleClient
    networks:
      risknet:
    depends_on:
    - risk.api


  


  stuartclient:
    hostname: stuartclient
    image: ${DOCKER_REGISTRY-}stuartclient
    build:
      context: .
      dockerfile: StuartClient/Dockerfile
    ports:
    - "5020:80"
    environment:
    - GameServer=http://risk.api
    - ClientCallbackAddress=http://stuartclient
    - userName=Stuart
    networks:
      risknet:
    depends_on:
    - risk.api


  
#  kaydonsclient:
#    hostname: kaydonclient
#    image: ${DOCKER_REGISTRY-}kaydonsclient
#    build:
#      context: .
#      dockerfile: Kaydon'sClient/Dockerfile
#    ports:
#    - "5040:80"
#    environment:
#    - GameServer=http://risk.api
#    - ClientCallbackAddress=http://kaydonsclient
#    - PlayerName=Kaydon
#    networks:
#      risknet:
#    depends_on:
#    - risk.api

  emmanuel_client:
    hostname: emmanuel_client
    image: ${DOCKER_REGISTRY-}emmanuelclient
    build:
      context: .
      dockerfile: clients/Emmanuel_Client/Dockerfile
    ports:
    - "5045:80"
    environment:
    - GameServer=http://risk.api
    - ClientCallbackAddress=http://emmanuel_client
    - PlayerName=Emmanuel
    networks:
      risknet:
    depends_on:
    - risk.api

  

networks:
  risknet:





